
import 'package:get/get.dart';
class MyTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      'Login' : 'Login',
      'Email' : 'Email',
      'Password' :'Password',
      "Don't have an account?" : "Don't have an account?",
      'Register':'Register',
      'First Name' : 'First Name',
      'Second Name':'Second Name',
      'Type':'Type',
      'Doctor':'Doctor',
      'patient' : 'patient',
      "please select a type":"please select a type",
      'Medical Record' : 'Medical Record',
      'Medicine Taken' : 'Medicine Taken',
      'Specialization' :'Specialization',
      "Register done🎉": "Register done🎉",
      "Register error":"Register error",
      "fail in login": "fail in login",
      "UserName is not found ": "UserName is not found ",
      'Password is not correct' : 'Password is not correct',
      'can not loading' : 'can not loading',
      'User type not found' : 'User type not found',
      'welcome,': 'welcome,',
      'Error loading appointment':'Error loading appointment',
      "Appointment booked successfully" : "Appointment booked successfully",
      'Make Appointment':'Make Appointment',
      "Appointment cancelled successfully" : "Appointment cancelled successfully",
      'Accept':'Accept',
      "Accepted":"Accepted",
      'Cancel':'Cancel',
      "Logout failed":"Logout failed",
      'No appointments yet':'No appointments yet',
      "Your appointment has been accepted by Dr.":"Your appointment has been accepted by Dr.",
      "Notifications":"Notifications",
      "No notifications yet.":"No notifications yet.",
      'Cardiology': 'Cardiology',
  'Neurology': 'Neurology',
  'Pediatrics': 'Pediatrics',
  'Orthopedics': 'Orthopedics',
  'Oncology': 'Oncology',
  'Radiology': 'Radiology',
  'Internal Medicine': 'Internal Medicine',
  'General Surgery': 'General Surgery',
  'Dermatology': 'Dermatology',
  'Psychiatry': 'Psychiatry',
  'Ophthalmology': 'Ophthalmology',
  'ENT': 'ENT',
  'Gynecology': 'Gynecology',
  'Urology': 'Urology',
  'Anesthesiology': 'Anesthesiology',
  'Family Medicine': 'Family Medicine',
  'Emergency Medicine': 'Emergency Medicine',
 "Please select a category":"Please select a category",
    },
    'ar': {
      'Login': 'تسجيل دخول',
      'Email' : 'الايميل',
      'Password' : 'كلمه السر ',
      "Don't have an account?": "ليس لديك حساب؟",
      'Register' : "سجل ",
      'First Name': "الاسم الاول ",
      'Second Name' : "الاسم الثانى",
      'Type': "النوع",
      'Doctor' : "دكتور",
      'patient': "مريض",
      "please select a type": "من فضلك اختر النوع",
      'Medical Record': "السجل المرضى",
      'Medicine Taken': "دواء مستمر",
      'Specialization' : "التخصص",
      "Register done🎉": "تم انشاء حساب 🎉",
      "Register error":"خطاء فى انشاء الحساب ",
      "fail in login": "خطاء فى تسجيل الدخول ",
      "UserName is not found ": "المستحدم غير موجود",
      'Password is not correct':"كلمه السر خطأ",
      'can not loading': "لا نستطع تسجيل الدخول ",
      'User type not found' : "المستخدم غير موجود",
      'welcome,': 'أهلاً بك',
      'Error loading appointment': "خطا فى الحجز",
      "Appointment booked successfully": "تم الحجز بنجاح",
      'Make Appointment': " احجز",
      "Appointment cancelled successfully": "تم اللغاء الحجز بنجاح",
      'Accept':"قبول",
      'Accepted': "قبل",
      'Cancel': "اللغاء",
      "Logout failed": "فشل فى تسجسل الخروج",
      'No appointments yet':"ليس يوجود حجوزات الى الان",
      "Your appointment has been accepted by Dr.":"تم قبول الحجز من الدكتور",
      "Your appointment has been cancelled by Dr.":"تم رفض الحجز من  الدكتور",
      "Notifications": "الاشعارات",
      "No notifications yet" : "ليس يوجد اشعارات الى الان",
      'Cardiology': 'أمراض القلب',
  'Neurology': 'الأعصاب',
  'Pediatrics': 'طب الأطفال',
  'Orthopedics': 'جراحة العظام',
  'Oncology': 'الأورام',
  'Radiology': 'الأشعة',
  'Internal Medicine': 'الطب الباطني',
  'General Surgery': 'الجراحة العامة',
  'Dermatology': 'الأمراض الجلدية',
  'Psychiatry': 'الطب النفسي',
  'Ophthalmology': 'طب العيون',
  'ENT': 'الأنف والأذن والحنجرة',
  'Gynecology': 'أمراض النساء',
  'Urology': 'جراحة المسالك البولية',
  'Anesthesiology': 'التخدير',
  'Family Medicine': 'طب الأسرة',
  'Emergency Medicine': 'طب الطوارئ',
  "Please select a category": 'من فضلك اختار فئه',
    }
  };
}

  /*static String currentLang = 'en'; 

  static String getText(String key) {
    return localizedValues[currentLang]?[key] ?? key;
  }

  void toggleLang() {
    currentLang = currentLang == 'en' ? 'ar' : 'en';
    notifyListeners(); 
  }
}*/
